// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model_ViewModel.Models;

namespace Model_ViewModel.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220712162220_CreateTables")]
    partial class CreateTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model_ViewModel.Models.Category", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryID");

                    b.Property<string>("CategoryName");

                    b.HasKey("Guid");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Model_ViewModel.Models.Degree", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DegreeID");

                    b.Property<string>("DegreeName");

                    b.HasKey("Guid");

                    b.ToTable("Degree");
                });

            modelBuilder.Entity("Model_ViewModel.Models.Person", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired();

                    b.Property<int>("Degree");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Gender");

                    b.Property<bool>("IAccept");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.Property<string>("Website")
                        .IsRequired();

                    b.HasKey("Guid");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Model_ViewModel.Models.Product", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CategoryGuid");

                    b.Property<DateTime>("CreateDate");

                    b.Property<int>("Deleted");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<Guid?>("PersonGuid");

                    b.Property<int>("ProductCategoryID");

                    b.Property<string>("ProductDesc");

                    b.Property<int>("ProductID");

                    b.Property<string>("ProductImage");

                    b.Property<string>("ProductName");

                    b.Property<long>("ProductPrice");

                    b.Property<string>("ProductShortDesc");

                    b.HasKey("Guid");

                    b.HasIndex("CategoryGuid");

                    b.HasIndex("PersonGuid");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Model_ViewModel.Models.Product", b =>
                {
                    b.HasOne("Model_ViewModel.Models.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryGuid");

                    b.HasOne("Model_ViewModel.Models.Person", "Person")
                        .WithMany("Product")
                        .HasForeignKey("PersonGuid");
                });
#pragma warning restore 612, 618
        }
    }
}
